#!/bin/bash


for file in /home/ubuntu/forloop/*  # taking all the files in the directory as a std input
do
        tar -czvf $file-$(date +%Y-%M).tar.gz "$file"  # zipping the files in one single file 
        echo "Backup is created on $(date)"  
        sleep 1m    # backup interval can be chnaged as per the requirement 
done
